language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vamsisis/docker-react -f Dockerfile.dev .

script:
  - docker run -e vamsisis/docker-react npm run test -- --coverage
  

