sudo: required
language: ruby
rvm:
 - 2.2
 - jruby 
services:
    - docker 

before_install:
    - docker build -t MYIMAGE/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true MYIMAGE/docker-react npm run test
