[global_tags]

[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "s"
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

[[outputs.prometheus_client]]
  listen = ":9273"
  collectors_exclude = ["gocollector", "process"]
  string_as_label = true

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  report_active = false
  fielddrop = ["usage_guest","usage_guest_nice","usage_iowait","usage_irq","usage_nice","usage_softirq","usage_steal","usage_system","usage_user"]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

[[inputs.mem]]
  fielddrop = ["active","available","available_percent","buffered","cached","commit_limit","committed_as","dirty","free","high_free","high_total","huge_page_size","huge_pages_free","huge_pages_total","inactive","low_free","low_total","mapped","page_tables","shared","slab","swap_cached","swap_free","swap_total","used","vmalloc_chunk","vmalloc_total","vmalloc_used","wired","write_back","write_back_tmp"]

[[inputs.processes]]
  fielddrop = ["blocked","paging","unknown","total_threads"]

[[inputs.swap]]
  fielddrop = ["free","used","in","out"]

[[inputs.system]]
  fielddrop = ["uptime","load1","load5","load15"]
